/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_MYCLIENT_H_
#define JSONRPC_CPP_STUB_MYCLIENT_H_

#include <jsonrpccpp/client.h>

class MyClient : public jsonrpc::Client
{
    public:
        MyClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        Json::Value request(const Json::Value& json_object) 
        {
            Json::Value p;
            p["json_object"] = json_object;
            Json::Value result = this->CallMethod("request",p);
            if (result.isObject())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
};

#endif //JSONRPC_CPP_STUB_MYCLIENT_H_
