/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_MYSERVER_H_
#define JSONRPC_CPP_STUB_MYSERVER_H_

#include <jsonrpccpp/server.h>

class MyServer : public jsonrpc::AbstractServer<MyServer>
{
    public:
        MyServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<MyServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("request", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_OBJECT, "json_object",jsonrpc::JSON_OBJECT, NULL), &MyServer::requestI);
        }

        inline virtual void requestI(const Json::Value &request, Json::Value &response)
        {
            response = this->request(request["json_object"]);
        }
        virtual Json::Value request(const Json::Value& json_object) = 0;
};

#endif //JSONRPC_CPP_STUB_MYSERVER_H_
